import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Generated from the folder structure rather than listed by hand.
 *
 * Order comes from `sidebar_position` in a page's front matter, or from a
 * `_category_.json` in a folder. Swap this for an explicit list when the order needs an argument.
 */
const sidebars: SidebarsConfig = {
    docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
